### PR TITLE
Adding our status page to footer.

### PR DESCRIPTION
**Pull request by myrdinm**
Link to [our status page](http://status.clic2000.fr) in our footers.

### CODE REVIEW

**Comment by myrdinm** [comment]
You are right. I'm on it.

**Comment by myrdinm** [comment]
@mthld done in d2580ce

**Comment by mthld** [comment]
@myrdinm you leave the English one like this?

**Comment by myrdinm** [comment]
forgot these 🙄

**Comment by myrdinm** [comment]
@mthld better now

**Pull request merged**
